### ISSUE TITLE
使用docker构建，创建块中的余额都给了哪个账号呢？

### ISSUE THREAD

**Issue by ddzyan** [iost-official/go-iost#1016]
我构建使用的指令是“sudo docker run -it --rm -p 30000-30003:30000-30003 iostio/iost-node”

查询admin账号余额为0

**Comment by QwertyJack** [comment]
你怎么查的？

**Comment by QwertyJack** [comment]
不妨试试另开一个终端，执行：
- 登录容器: `docker exec -it <container-name> bash`
- 查询余额: `iwallet balance admin`
