### ISSUE TITLE
build iost success,But run failed

### ISSUE THREAD

**Issue by JKinGH** [iost-official/go-iost#1082]
![iost](https://user-images.githubusercontent.com/41677975/57273759-97440480-70cb-11e9-906f-68f7eac59428.jpg)

**Comment by lispc** [comment]
https://developers.iost.io/docs/en/4-running-iost-node/Building-IOST.html#build-iost
one dylib should be installed

**Comment by JKinGH** [comment]
> https://developers.iost.io/docs/en/4-running-iost-node/Building-IOST.html#build-iost
> one dylib should be installed

Thanks,is ok now. But I find the CN docs be diff from EN docs like https://developers.iost.io/docs/zh-CN/4-running-iost-node/Building-IOST.html#%E7%BC%96%E8%AF%91
In addition，can you invite me to join iost slack please? my email is gg13128805423@gmail.com

**Comment by QwertyJack** [comment]
@JKinGH Problem solved ?

**Comment by JKinGH** [comment]
> @JKinGH Problem solved ?

solved, thx
