### ISSUE TITLE
iwallet's chain_id error

### ISSUE THREAD

**Issue by aker0357** [iost-official/go-iost#1089]
ERROR: send tx error rpc error: code = Unknown desc = VerifyError invalid chain_id, should be 1020, yours:1024
https://github.com/iost-official/go-iost/blob/master/iwallet/root.go#L83

```	rootCmd.PersistentFlags().Uint32VarP(&chainID, "chain_id", "", uint32(1024), "chain id which distinguishes different network")```

at root.go chainId should be 1020

**Comment by ziranliu** [comment]
It should be 1024 since the iwallet is build for mainnet. If you want to use it in other network, add `--chain_id xxx` in the command

**Comment by aker0357** [comment]
thanks
