### ISSUE TITLE
区块扫描

### ISSUE THREAD

**Issue by huachao0326** [iost-official/go-iost#1092]
获取充值只能一个块一个块的扫描吗？
还是有类似EOS的方式获取账户充值信息？

**Comment by ziranliu** [comment]
通过链上的接口只能一个块一个块的扫描，如果要获取某个账户的历史交易，需要调用链下的一些第三方接口，比如一些浏览器的提供的 api

**Comment by huachao0326** [comment]
好的，谢谢
