### ISSUE TITLE
iost开发团队解散了吗？

### ISSUE THREAD

**Issue by Aoseala** [iost-official/go-iost#1094]
iost开发团队解散了吗，这么多天都不更新代码，放弃了吗？

**Comment by lileicool1** [comment]
The team is developing and testing the v3.2.0 version. At least one release version per month .

**Comment by lileicool1** [comment]
> iost开发团队解散了吗，这么多天都不更新代码，放弃了吗？

The team is developing and testing the v3.2.0 version. At least one release version per month .
