### ISSUE TITLE
use iwallet block xxx get an empty transactions?

### ISSUE THREAD

**Issue by Alteryy** [iost-official/go-iost#1096]
iost/iwallet block 24609769
Connecting to server localhost:30002 ...
{
    "status": "IRREVERSIBLE",
    "block": {
        "hash": "94i3zmcCX8h8W9ZFU9BFhGMB47JWjNh5rBUyFgsqRRV",
        "version": "1",
        "parentHash": "DEATaAZTFEMPAeVUSX1yEK7iCBiA2SMBV2rLcPNcrtTK",
        "txMerkleHash": "8iQ15Nm44Nu2BehnZ1mKmSbECgHmwWXyYn8oaFUMEp55",
        "txReceiptMerkleHash": "3besk5QX5NuHvYdWAUyMBgpvKkKTkRuwbuxr6aThkiVg",
        "number": "24609769",
        "witness": "31ibPtxBLW5e7yTsV9XSDVZ5Hs5w9n7UtHNzXpuP7EUB",
        "time": "1562401728500118898",
        "gasUsage": 0,
        "txCount": "3",
        "info": {
            "mode": 0,
            "thread": 0,
            "batchIndex": [
            ]
        },
        "transactions": [
        ]
    }
}
why transactions is empty? txCount is 3?

**Comment by ccding** [comment]
The API is /getBlockByHash/{hash}/{complete}

please set {complete} to true

**Comment by ccding** [comment]
the same for `iwallet` command line tool: set the following flag to `true`

```
-c, --complete        indicate whether to fetch all the transactions in the block or not
```

**Comment by Alteryy** [comment]
> true

thx, Solved it.
