### ISSUE TITLE
error: token iost exceed amountLimit in ab

### ISSUE THREAD

**Issue by tvrc4m** [iost-official/go-iost#1102]
call deposit in contract.
blockchain.deposit(player, _betAmount, "bet")

Transaction has been sent.
The transaction hash is: 2aHJ4FDGPa7vZA1XYKi6hMgF5mSGwHgeaL84hZphhQaP
Checking transaction receipt...
Transaction receipt:
{
    "txHash": "2aHJ4FDGPa7vZA1XYKi6hMgF5mSGwHgeaL84hZphhQaP",
    "gasUsage": 56841,
    "ramUsage": {
    },
    "statusCode": "RUNTIME_ERROR",
    "message": "running action Action{Contract: ContractCVxupPS8NQTrNZ97kT71gGvCZU4F5edkdYjoSPgcfeV2, ActionName: bet, Data: [\"game... error: token iost exceed amountLimit in abi. need 10",
    "returns": [
    ],
    "receipts": [
    ]
}
Transaction executed err

**Comment by ziranliu** [comment]
If a function of contract takes user's token, you have to declare amount limit in the abi, just like: https://github.com/iost-official/go-iost/blob/master/config/genesis/contract/vote_producer.js.abi#L108

**Comment by tvrc4m** [comment]
@ziranliu  thanks you. it's ok
how auto generate it ?
"amountLimit": [{
    "token": "iost",
     "val": "unlimited"
}],

**Comment by ziranliu** [comment]
> @ziranliu thanks you. it's ok
> how auto generate it ?
> "amountLimit": [{
> "token": "iost",
> "val": "unlimited"
> }],

You have to add it in abi manually

**Comment by tvrc4m** [comment]
ok. and iost support delay transaction?

**Comment by ziranliu** [comment]
> ok. and iost support delay transaction?

no
