### ISSUE TITLE
How do I get an account for testnet and mainnet?

### ISSUE THREAD

**Issue by wshhz** [iost-official/go-iost#1103]
I failed to apply for an account on this website(https://testnet.explorer.iost.io/applyIOST).

**Comment by ziranliu** [comment]
Could you provide more information about why you failed?
The faucet of testnet needs google captcha. So you'd better use a proxy to visit it.

**Comment by wshhz** [comment]
> Could you provide more information about why you failed?
> The faucet of testnet needs google captcha. So you'd better use a proxy to visit it.
I don't have proxy,can you help me to create a test account?

**Comment by ziranliu** [comment]
Sure. It's not suitable to discuss here. You can send your desired account name and pubkey to me by email (ziran@iost.io).
