### ISSUE TITLE
测试网和主网的节点同步下来大概会占用多少硬盘空间？

### ISSUE THREAD

**Issue by wshhz** [iost-official/go-iost#1105]
我在本地搭建了测试网络的节点，但是同步块的速度实在是太慢了，想问一下现在的数据量大概有多大？

**Comment by ziranliu** [comment]
测试网 30GB 左右，可以下载 snapshot 加速同步：https://developers.iost.io/docs/en/4-running-iost-node/Deployment.html#using-snapshot-to-accelerate-synchronization

测试网下载链接是 http://archive.iost.io/snapshot/testnet/storage.tar

**Comment by wshhz** [comment]
主网大概有多大呢？

**Comment by ziranliu** [comment]
100GB 左右

**Comment by wshhz** [comment]
好的，谢谢了
