### ISSUE TITLE
iost 节点同步 

### ISSUE THREAD

**Issue by jade-chain** [iost-official/go-iost#1116]
Syncing block in [38499939 38500938]...
一直无法同步成功
版本3.3.0
已经好几天了，日志都是这样
Info 2019-09-28 13:04:17.457 sync.go:170 Syncing block in [38499939 38500938]...
Info 2019-09-28 13:04:19.457 sync.go:170 Syncing block in [38499939 38500938]...
Info 2019-09-28 13:04:21.457 sync.go:170 Syncing block in [38499939 38500938]...
Info 2019-09-28 13:04:23.457 sync.go:170 Syncing block in [38499939 38500938]...
Info 2019-09-28 13:04:25.457 sync.go:170 Syncing block in [38499939 38500938]...
Info 2019-09-28 13:04:27.458 sync.go:170 Syncing block in [38499939 38500938]...
Info 2019-09-28 13:04:29.481 sync.go:170 Syncing block in [38499939 38500938]...
Info 2019-09-28 13:04:31.483 sync.go:170 Syncing block in [38499939 38500938]...

**Comment by jade-chain** [comment]
iserver.xml
acc:
  id: visiter00 
  seckey: 21h8pQe7kg4ATH6Krh2BXorAj7E5SvF5KdFiCghUByjFEEUKrL8Fmig331NqdNveoiCwhmuxoWnCV7pdu96epork
  algorithm: ed25519
genesis: /iost/iserver/genesis 
vm:
  jspath: /iost/src/github.com/iost-official/go-iost/vm/v8vm/v8/libjs/ 
  loglevel: ""
  maxTxLimitTime: 200
db:
  ldbpath: /iost/iserver/storage/
snapshot:
  enable: false
  filepath: storage/snapshot.tar.gz
p2p:
  listenaddr: 0.0.0.0:30000
  seednodes:
    - /ip4/18.209.137.246/tcp/30000/ipfs/12D3KooWGoPE333zygBN61vtSjvPfosi78JFSwRRDrLoAKaH1mTP   # United States
    - /ip4/54.180.196.80/tcp/30000/ipfs/12D3KooWMm2RzyZDPBie89FXceKFSBRg8zzkwAGQmdauj6tmrqcA    # Korea
    - /ip4/35.176.24.11/tcp/30000/ipfs/12D3KooWHzHUBq4x4LmXtZH79LCAxVUYgpKXgMgAtyvYQWeHZAAp     # England
  chainid: 1024
  version: 1
  datapath: /iost/iserver/p2p/ 
  inboundConn: 30
  outboundConn: 30
  blackPID:
  blackIP:
  adminPort: 30005
rpc:
  enable: true
  gatewayaddr: 127.0.0.1:30001
  grpcaddr: 127.0.0.1:30002
  trytx: false
  exectx: false
  allowOrigins:
    - "*"
log:
  filelog:
    path: /iost/iserver/logs/ 
    level: info 
    enable: true
  consolelog:
    level: error 
    enable: true
  asyncwrite: true
  enablecontractlog: true
metrics:
  pushAddr: pushgateway
  username:
  password:
  enable: false
  id: mainnet:visiter00
debug:
  listenaddr: 127.0.0.1:30003
version:
  netname: mainnet 
  protocolversion: "1.0"

**Comment by zzzzzzzmt** [comment]
hi,你是怎么解决的 我停在同一个区块
