### ISSUE TITLE
why version update to v3.3.5 but don't have any news?

### ISSUE THREAD

**Issue by wshhz** [iost-official/go-iost#1150]
I want to know why there is v3.3.5 version of the code, and now there is a problem with the v3.3.4 version of the code? Should I use the v3.3.4 version of the code now or wait for the update?

**Comment by lispc** [comment]
It is a hotfix in hurry.

**Comment by lispc** [comment]
You can wait for several hours for the final 3.3.5 release

**Comment by wshhz** [comment]
更新和网络升级有关系吗？我看火币交易所发的公告是主网升级

**Comment by lispc** [comment]
一个意思吧。fix了就有新版本，就主网升级了。

**Comment by wshhz** [comment]
好的了解了
