### ISSUE TITLE
Building IOST fails with "flag provided but not defined: -mod" error

### ISSUE THREAD

**Issue by tunga0** [iost-official/go-iost#1174]
I am raising this issue because the instructions mentioned here https://developers.iost.io/docs/en/4-running-iost-node/Building-IOST.html are failing.

**Steps to reproduce the issue:**

teemav@tungaVm1:~$ export GOPATH=$(go env GOPATH)

teemav@tungaVm1:~$ export PATH=$PATH:$GOPATH/bin

teemav@tungaVm1:~$ mkdir -p $GOPATH/github.com/iost-official/
mkdir: cannot create directory ‘/home/teemav/go/github.com/iost-official/’: No such file or directory

teemav@tungaVm1:~$ cd $GOPATH/github.com/iost-official/

teemav@tungaVm1:~/go/github.com/iost-official$ pwd
/home/teemav/go/github.com/iost-official

teemav@tungaVm1:~/go/github.com/iost-official$ git clone https://github.com/iost-official/go-iost.git
```
Cloning into 'go-iost'...
remote: Enumerating objects: 158, done.
remote: Counting objects: 100% (158/158), done.
remote: Compressing objects: 100% (128/128), done.
remote: Total 60750 (delta 53), reused 64 (delta 30), pack-reused 60592
Receiving objects: 100% (60750/60750), 139.91 MiB | 22.56 MiB/s, done.
Resolving deltas: 100% (39725/39725), done.
```
teemav@tungaVm1:~/go/github.com/iost-official$ cd go-iost/

teemav@tungaVm1:~/go/github.com/iost-official/go-iost$ ls
```
CHANGELOG.md  Dockerfile.dev  LICENSE   README.md  build      cmd     config     core    db      go.sum  iserver  iwallet  p2p  script  test   vendor    vm
Dockerfile    Dockerfile.run  Makefile  account    chainbase  common  consensus  crypto  go.mod  ilog    itest    metrics  rpc  sdk     tools  verifier
```

teemav@tungaVm1:~/go/github.com/iost-official/go-iost$ git lfs pull
Git LFS: (15 of 15 files) 62.01 MB / 62.01 MB

teemav@tungaVm1:~/go/github.com/iost-official/go-iost$ ls
```
CHANGELOG.md  Dockerfile.dev  LICENSE   README.md  build      cmd     config     core    db      go.sum  iserver  iwallet  p2p  script  test   vendor    vm
Dockerfile    Dockerfile.run  Makefile  account    chainbase  common  consensus  crypto  go.mod  ilog    itest    metrics  rpc  sdk     tools  verifier

```
teemav@tungaVm1:~/go/github.com/iost-official/go-iost$ cd vm/v8vm/v8/; make deploy; cd ../../..
```
sudo install ./libv8/_linux_amd64/*.so /usr/local/lib
sudo /sbin/ldconfig

```

teemav@tungaVm1:~/go/github.com/iost-official/go-iost$ pwd
/home/teemav/go/github.com/iost-official/go-iost

teemav@tungaVm1:~/go/github.com/iost-official/go-iost$ make build install
```
**go build -mod vendor -ldflags "-X github.com/iost-official/go-iost/core/global.BuildTime=20210109_001016+0000 -X github.com/iost-official/go-iost/core/global.GitHash=472164d0856286fbc7bec3d90e31bed61a8b0b90 -X github.com/iost-official/go-iost/core/global.CodeVersion=3.4.0" -o target/iserver github.com/iost-official/go-iost/cmd/iserver
flag provided but not defined: -mod
usage: build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
Makefile:36: recipe for target 'iserver' failed
make: *** [iserver] Error 2**
```
teemav@tungaVm1:~/go/github.com/iost-official/go-iost$

teemav@tungaVm1:~/go/github.com/iost-official/go-iost$ pwd
`/home/teemav/go/github.com/iost-official/go-iost`

teemav@tungaVm1:~/go/github.com/iost-official/go-iost$ uname -a
Linux tungaVm1 5.4.0-1034-azure #35~18.04.1-Ubuntu SMP Thu Dec 10 09:13:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
teemav@tungaVm1:~/go/github.com/iost-official/go-iost$ cat /etc/os-release
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
teemav@tungaVm1:~/go/github.com/iost-official/go-iost$ go version
go version go1.10.4 linux/amd64
teemav@tungaVm1:~/go/github.com/iost-official/go-iost
```$

**Comment by lispc** [comment]
Your Golang is 1.10 it is too old.  We support Golang 1.13 and later

**Comment by tunga0** [comment]
thanks
