### ISSUE TITLE
What's the case when Blockchain.deposit method returns not 0 value.

### ISSUE THREAD

**Issue by nujabes403** [iost-official/go-iost#295]
https://github.com/iost-official/go-iost/blob/d08eba08b2cd6ff70fa590094ff287b941e6c02b/vm/test_data/lucky_bet.js#L27

`Blockchain.deposit` seems return 0, when it successes to deposit.
However, if not, what values will be returned from Blockchain.deposit, does it return some error code explaining cause of error? ex:) 107: 'user already bet', 108: 'user doesn't exist..' etc..

@flybikeGx @lispc

**Comment by sswsdsn** [comment]
Blockchain is a JavaScript Class, and all it's methods like deposit are implemented by V8VM, also Blockchain class is an underlying implementation,  it has nothing to do with lucky_bet, you can find all it's error code here: [vm/v8vm/blockchain.go](https://github.com/iost-official/go-iost/blob/develop/vm/v8vm/blockchain.go#L16)

**Comment by nujabes403** [comment]
@sswsdsn Cool!
