### ISSUE TITLE
Lucky_bet userNumber counting up

### ISSUE THREAD

**Issue by nujabes403** [iost-official/go-iost#296]
https://github.com/iost-official/go-iost/blob/d08eba08b2cd6ff70fa590094ff287b941e6c02b/vm/test_data/lucky_bet.js#L40

Is it ok to count up userNumber even if same account bet twice?
Is there any logic in contract to prevent betting twice per user?

**Comment by flybikeGx** [comment]
In our design this field means the bet times in a round, no matter who bets.
More accurate name of this field would be updated soon.
