### ISSUE TITLE
v8 linking error

### ISSUE THREAD

**Issue by crazybits** [iost-official/go-iost#700]
the following error is prompted when run the test case of genesis_test.go on mac 10.13.6, any hint would be appreciated

`# github.com/iost-official/go-iost/vm/v8vm
ld: warning: ignoring file ../../vm/v8vm/v8/libv8/_darwin_amd64/libvm.dylib, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): ../../vm/v8vm/v8/libv8/_darwin_amd64/libvm.dylib
Undefined symbols for architecture x86_64:
  "_Execute", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_Execute in _x006.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_Execute)
  "_InitGoBlockchain", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_InitGoBlockchain in _x006.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_InitGoBlockchain)
  "_InitGoConsole", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_InitGoConsole in _x006.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_InitGoConsole)
  "_InitGoCrypto", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_InitGoCrypto in _x006.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_InitGoCrypto)
  "_InitGoStorage", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_InitGoStorage in _x006.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_InitGoStorage)
  "_compile", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_compile in _x006.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_compile)
  "_createCompileStartupData", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_createCompileStartupData in _x008.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_createCompileStartupData)
  "_createStartupData", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_createStartupData in _x008.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_createStartupData)
  "_init", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_init in _x008.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_init, __cgo_wait_runtime_init_done )
  "_loadVM", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_loadVM in _x006.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_loadVM)
  "_lowMemoryNotification", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_lowMemoryNotification in _x008.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_lowMemoryNotification)
  "_newIsolate", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_newIsolate in _x008.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_newIsolate)
  "_newSandbox", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_newSandbox in _x006.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_newSandbox)
  "_releaseIsolate", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_releaseIsolate in _x008.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_releaseIsolate)
  "_releaseSandbox", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_releaseSandbox in _x006.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_releaseSandbox)
  "_setJSPath", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_setJSPath in _x006.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_setJSPath)
  "_setSandboxGasLimit", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_setSandboxGasLimit in _x006.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_setSandboxGasLimit)
  "_validate", referenced from:
      __cgo_6cadb3e0a99b_Cfunc_validate in _x006.o
     (maybe you meant: __cgo_6cadb3e0a99b_Cfunc_validate)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by nujabes403** [comment]
@crazybits 
Did you install dynamic library by typing `$ make vmlib` ?

**Comment by crazybits** [comment]
@nujabes403 make vmlib failed with the following error
 `clang++ -g -std=c++11 -fno-rtti -fPIC -m64 -Wall -Wextra -Wno-unused-parameter -Wno-unused-result -O3 -I./include/common -I./libjs/include -I./include/_darwin_amd64 -c crypto.cc -o crypto.cc.o
clang++ -g -shared -fvisibility=hidden vm.cc.o allocator.cc.o console.cc.o require.cc.o storage.cc.o blockchain.cc.o sandbox.cc.o instruction.cc.o compile.cc.o crypto.cc.o -o libvm.dylib -L./libv8/_darwin_amd64 -lv8_libbase -lv8_libplatform -lv8_init -lv8_initializers -lv8_libsampler -lv8_snapshot -lv8_base 
ld: warning: ld: warning: ld: warning: ld: warning: ignoring file ./libv8/_darwin_amd64/libv8_init.a, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): ./libv8/_darwin_amd64/libv8_init.aignoring file ./libv8/_darwin_amd64/libv8_libplatform.a, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): ./libv8/_darwin_amd64/libv8_libplatform.aignoring file ./libv8/_darwin_amd64/libv8_initializers.a, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): ./libv8/_darwin_amd64/libv8_initializers.aignoring file ./libv8/_darwin_amd64/libv8_libbase.a, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): ./libv8/_darwin_amd64/libv8_libbase.a



ld: warning: ignoring file ./libv8/_darwin_amd64/libv8_base.a, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): ./libv8/_darwin_amd64/libv8_base.a
ld: warning: ignoring file ./libv8/_darwin_amd64/libv8_snapshot.a, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): ./libv8/_darwin_amd64/libv8_snapshot.a
ld: warning: ignoring file ./libv8/_darwin_amd64/libv8_libsampler.a, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): ./libv8/_darwin_amd64/libv8_libsampler.a
Undefined symbols for architecture x86_64:

....


ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

`

**Comment by nujabes403** [comment]
https://iost-community.slack.com/archives/CCXFAMQ0K/p1546358897265400?thread_ts=1546330892.250600&cid=CCXFAMQ0K

It seems your issue is same with Aladdin's. He said it was solved by removing whole folder, following the steps again.

Could you remove whole folder, and do it again step by step?
1. `brew install git-lfs`
2. `git lfs install`
3. `brew install rocksdb`
4. `git clone git@github.com:iost-official/go-iost.git`
5. `make vmlib`
6. `make build`

**Comment by crazybits** [comment]
@nujabes403 awesome, issue solved, thanks

**Comment by QwertyJack** [comment]
`rocksdb` is abondoned since v2.1.0
