### ISSUE TITLE
blockchain.transfer fail when passing float number

### ISSUE THREAD

**Issue by YUANLIN327** [iost-official/go-iost#924]
In the smart contract, when tried something like this
``` javascript
const account = 'exampleaccount'
const amount = 2.6;
const memo = ''
blockchain.deposit(account, amount, memo)
```
It will fail.

The transfer method won't accept a float number as the amount parameter.

![image](https://user-images.githubusercontent.com/12224909/53663430-bdfd3f00-3c33-11e9-9e4a-6542da7cad88.png)

**Comment by lispc** [comment]
current API only supports string.
2.6 -> "2.6"
