### ISSUE TITLE
iwallet import account conflict between Mainnet & Testnet

### ISSUE THREAD

**Issue by LingTian** [iost-official/go-iost#934]
This issue cause by mainnet & testnet share same account name. For my case I use whitematrix for both mainnet & testnet. After I import whitematrix for testnet, I cannot import it for mainnet.

**Comment by LingTian** [comment]
My hacky way to solve this is goto /Users/username/.iwallet and get rid of the conflict account. Remeber to save your private key first.
I think iwallet can add some flags to solve this issue

**Comment by lispc** [comment]
iwallet has a flag 'account_dir'. Private keys will be saved inside this dir.
So you can use a different account_dir for a different network
