### ISSUE TITLE
iserver build error Mac OSX Mohave 10.14.1

### ISSUE THREAD

**Issue by IOSTBRO** [iost-official/go-iost#943]
Following the instructions in: https://developers.iost.io/docs/en/4-running-iost-node/Building-IOST.html

Everything works fine, including the last step, which is: `make build install`

I can run `iwallet` and `itest` with no issues. However when I try to run `iserver` or `iserver -f ./config/iserver.yml` I get:

```
dyld: Library not loaded: libvm.dylib
  Referenced from: /Users/XXX/go/bin/iserver
  Reason: image not found
Abort trap: 6
```

Not sure how to load / install this library so that I can run the local node.

**Comment by QwertyJack** [comment]
Do you install `git-lfs` ?

**Comment by IOSTBRO** [comment]
Yes, that was installed. I solved it by doing a homebrew bulk update of all my packages, and that fixed the problem. Something must have been outdated. Thanks for the help

**Comment by aaronisme** [comment]
facing the same issue and the brew upgrade doesn't work
