### ISSUE TITLE
can not install iwallet 

### ISSUE THREAD

**Issue by FrankJoin** [iost-official/go-iost#993]
I want to install the iwallet, but it's not sucess.
![image](https://user-images.githubusercontent.com/38522016/54985349-9c516680-4feb-11e9-8acc-acda5d8fea07.png)

**Comment by QwertyJack** [comment]
Seems that `git` does not work well on Win.

That command actually does two things; you might do them sequentially:
1. download src: `go get github.com/iost-official/go-iost` or change dir to `$GOPATH/src/github.com/iost-official` then `git clone https://github.com/iost-official/go-iost`
2. install iwallet: change dir to `go-iost` and exec `go install ./cmd/iwallet`
