### ISSUE TITLE
无法安装iwallet

### ISSUE THREAD

**Issue by boy-good** [iost-official/go-iost#998]
根据官方文档的 go get github.com/iost-official/go-iost/cmd/iwallet
无法安装，执行命令毫无反应。

**Comment by boy-good** [comment]
有没有微信开发者群呢

**Comment by QwertyJack** [comment]
请检查网络是否畅通，另外请参考[golang官方文档](https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies)，或者[中文翻译](https://studygolang.com/articles/5690)。
